#!/bin/bash

GCOMPRIS_MAJOR_VERSION=`grep 'set(GCOMPRIS_MAJOR_VERSION' ../../CMakeLists.txt | cut -f1 -d\) | cut -f2 -d\ `
GCOMPRIS_MINOR_VERSION=`grep 'set(GCOMPRIS_MINOR_VERSION' ../../CMakeLists.txt | cut -f1 -d\) | cut -f2 -d\ `
GCOMPRIS_PATCH_VERSION=`grep 'set(GCOMPRIS_PATCH_VERSION' ../../CMakeLists.txt | cut -f1 -d\) | cut -f2 -d\ `
GCOMPRIS_VERSION="${GCOMPRIS_MAJOR_VERSION}.${GCOMPRIS_MINOR_VERSION}"
GCOMPRIS_VERSION_CODE=`expr ${GCOMPRIS_MAJOR_VERSION} \* 10000 + ${GCOMPRIS_MINOR_VERSION} \* 100 + ${GCOMPRIS_PATCH_VERSION}`

echo "GCOMPRIS_MAJOR_VERSION: ${GCOMPRIS_MAJOR_VERSION}"
echo "GCOMPRIS_MINOR_VERSION: ${GCOMPRIS_MINOR_VERSION}"
echo "GCOMPRIS_PATCH_VERSION: ${GCOMPRIS_PATCH_VERSION}"
echo "GCOMPRIS_VERSION: ${GCOMPRIS_VERSION}"
echo "GCOMPRIS_VERSION_CODE: ${GCOMPRIS_VERSION_CODE}"
